<div class="page-header">
    <div class="row">
        <div class="col-md-9">
        <h1>Data Pegawai</h1>
        </div>
        <div class="col-md-3">
            <?php if( $notif!="" ) { ?>
                <div class="alert alert-success" role="alert"><center><?=$notif?></center></div>
            <?php } ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title"><span id='ti'>TAMBAH</span> Data Pegawai</h3>
            </div>
            <div class="panel-body">
                <form action="index/proc" method="POST">
                    <div class="form-group">
                        <label for="nama">Nama Pegawai</label>
                        <input required type="text" class="form-control" name="nama" id="nama" placeholder="Nama Pegawai">
                    </div>
                    <div class="form-group">
                        <label for="jkel">Jenis Kelamin</label>
                        <select name="jkel" id="jkel" class="form-control">
                            <option value="L">Laki-laki</option>
                            <option value="P">Perempuan</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="ttl">Tanggal Lahir</label>
                        <input required type="date" class="form-control" name="ttl" id="ttl" placeholder="Tanggal Lahir">
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <textarea rows="3" class="form-control" name="alamat" id="alamat" placeholder="Alamat"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="nohp">No. HP</label>
                        <input required type="text" class="form-control" name="nohp" id="nohp" placeholder="No. HP">
                    </div>
                    <div class="form-group">
                        <label for="gaji">Gaji Pokok</label>
                        <input required type="number" class="form-control" name="gaji" id="gaji" placeholder="Gaji Pokok">
                    </div>
                    <input type="hidden" id="id" name="id">
                    <input type="hidden" id="act" name="act" value="crt">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">List Pegawai</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama Pegawai</th>
                                <th>Jenis Kelamin</th>
                                <th>Tanggal Lahir</th>
                                <th>Alamat</th>
                                <th>No. HP</th>
                                <th>Gaji Pokok</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if( count($data) == 0 ) { ?>
                                <tr><td colspan="8">Data masih kosong</td></tr>
                            <?php } ?>
                            <!-- {% for d in data %} -->
                            <?php
                                $no=1;
                                foreach ($data as $d) {
                            ?>
                                <tr>
                                    <td><?=$no++?></td>
                                    <td><?=$d->nama?></td>
                                    <td><?=($d->jkel == 'L') ? 'Laki-laki' : 'Perempuan'?></td>
                                    <td><?=$d->ttl?></td>
                                    <td><?=$d->alamat?></td>
                                    <td><?=$d->nohp?></td>
                                    <td><?=number_format($d->gaji, 0, ',', '.')?></td>
                                    <td>
                                        <a onclick="edit(`<?=$d->id?>`, `<?=$d->nama?>`, `<?=$d->jkel?>`, `<?=$d->ttl?>`, `<?=$d->alamat?>`, `<?=$d->nohp?>`, `<?=$d->gaji?>`)" href="javascript:;">
                                            <i style="cursor: pointer;" title="Ubah" class="glyphicon glyphicon-pencil"></i>
                                        </a>
                                        &nbsp;
                                        <a onclick="hapus(`<?=$d->id?>`, `<?=$d->nama?>`)" href="javascript:;">
                                            <i style="cursor: pointer;" title="Hapus" class="glyphicon glyphicon-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php
                                }
                            ?>
                            <!-- {% endfor %} -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    function hapus(id, nama) {
        var r = confirm("Yakin hapus data pegawai "+nama+"?");
        if (r == true) {
            location.href = "index/del/"+id
        }
    }

    function edit(id, nama, jkel, ttl, alamat, nohp, gaji) {
        $("#ti").html("EDIT");
        $("#act").val("upd");
        
        $("#id").val(id);
        $("#nama").val(nama);
        $("#jkel").val(jkel);
        $("#ttl").val(ttl);
        $("#alamat").val(alamat);
        $("#nohp").val(nohp);
        $("#gaji").val(gaji);
    }
</script>